### ISSUE TITLE
purpose of conf_thresh parameter in sample function is confusing

### ISSUE THREAD

**Issue by Tobimaru** [Parskatt/DKM#11]
Hello. Not completely sure if this is an issue, but I am a bit confused about what the `conf_thresh` parameter should be used for. I'm referring to [this line in dkm.py](https://github.com/Parskatt/DKM/blob/6b9b3781ef94d25d643561a2f603bcfe17e04f63/dkm/models/dkm.py#L525). Shouldn't this line come after the filtering with `relative_confidence_threshold`? Is it correct to say that `conf_thresh` filters out outliers and the inliers are given the same probability?

**Comment by Parskatt** [comment]
Yes, that is a good interpretation. Technically it should be after relative confidence threshold like you say, but in practice we use relative confidence threshold = 0, so it doesn't matter.

**Comment by Tobimaru** [comment]
Well it does matter I think if the behavior can be changed by the client 😅? I don't think the code will do what you expect with a relative confidence threshold that is non-zero, given that the confidence is already flattened above the `conf_thresh`. In any case, thank you for the feedback.

**Comment by Parskatt** [comment]
You're right :) The code we provide here is not without errors. I'll fix this issue in an upcoming release.
