### ISSUE TITLE
when demo dkmV3 release ?

### ISSUE THREAD

**Issue by QuanNguyen94** [Parskatt/DKM#13]
Hi, your great work is really amazing ! Can't wait for full release demo of DKMv3 . When do you intend to do that ?

**Comment by Parskatt** [comment]
Hi! Thanks for the kind words. We'll update with a simple demo soon :)

**Comment by Parskatt** [comment]
@QuanNguyen94 I fixed a simple demo to which you can supply a pair of images by commandline. In the future we'll make a fancier one :)
