### ISSUE TITLE
DKM:sample

### ISSUE THREAD

**Issue by scott-vsi** [Parskatt/DKM#18]
In DKM's [sample](https://github.com/Parskatt/DKM/blob/9ecffdb/dkm/models/dkm.py#L565) method, do you intend to set any certainty greater than 0.05 to 1, instead of, perhaps, setting any certainty less than 0.05 to 0?

https://github.com/Parskatt/DKM/blob/fb85d632c5aaa5be643717701016f31d3ac0af22/dkm/models/dkm.py#L574

I ask, because you then go on to sample from the matches based on that [certainty](https://github.com/Parskatt/DKM/blob/9ecffdb/dkm/models/dkm.py#L584) which can result in points with certainty less than 0.05 being sampled. In fact, if all the matches have certainty below 0.05, then `expansion_factor*num` matches would still be selected.

**Comment by Parskatt** [comment]
Hi!

Yes, this is intended. Although depending on the task you might want to use different types of thresholding. We found in general that it was better to "oversample" low confidence matches.

**Comment by scott-vsi** [comment]
Got it. Thank you!
