### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by ckLibra** [Parskatt/DKM#20]
Thanks for your great work and impressive results! 
Since your results are so impressive, it is straightforward to consider combing your work as part of the downstream task, like visual odometry. So I am curious about the inference time for DKM compared to other methods, like LoftR or optical flow method RAFT.  Have you done any experiments like this? I haven't seen any report about inference time in paper, so it will be so nice for you to help.

**Comment by Parskatt** [comment]
Hi!
The inference time is very much dependent on the resolution. At very high resolution (660x880), I think the FPS is about 2-5 (similar to LoFTR). At a lower resolution the inference is faster, perhaps 10 FPS at 384x512. If you are looking for high resolution output at low inference cost, I suggest using our option to run low internal resolution and upsampling the predictions with our scale one refiner.

Note that we have not focused on optimizing the current code, so there are big improvements to be made, such as half precision etc. We will update the codebase to run faster soon, after I finish some deadlines ;)

**Comment by ckLibra** [comment]
Thanks for your patient reply! It is very helpful. Wish everything goes well for you.
