### ISSUE TITLE
3d point projection, best way to fetch matches

### ISSUE THREAD

**Issue by drperpen** [Parskatt/DKM#23]
Hi,
I have known camera extrinsics/intrinsics and I like to 3d project the pixels of 2 images matched by DKM. What would be a good point to get the matches between the images?
Thanks!
Daniel

**Comment by Parskatt** [comment]
Matching will get you the 2D points, to project into 3D (triangulate) I recommend using e.g. kornia :)

**Comment by Parskatt** [comment]
Yes, they are normalized in the grid [-1,1]. To convert to pixel coordinates you probably want to do something like (x+1)*H/2.

**Comment by Parskatt** [comment]
Note that the internal resolution in DKM might not match the original resolution of the image.

**Comment by drperpen** [comment]
Thank you so much! Yes, I will have in mind DKM's internal resolution when doing the conversions.

**Comment by Parskatt** [comment]
I'll close for now :)
