### ISSUE TITLE
the structure and information of 'warp'

### ISSUE THREAD

**Issue by zzxq2310** [Parskatt/DKM#29]
I am performing an image matching test on demo_match.py. What is the structure of the warp obtained in this code ‘warp, certainty = dkm_model.match(im1_path, im2_path, device=device)’, and what is the information stored in it?I want to get the pixel matching relationship of two pictures through ‘warp’, how should I do it？Thank you very much!

**Comment by Parskatt** [comment]
The matches are produced in the normalized grid [-1,1]x[-1,1]. You can transform this to pixel coordinates by (x+1)*W/2 and (y+1)*H/2, for whatever H and W you want.

**Comment by Parskatt** [comment]
See also https://github.com/Parskatt/DKM/blob/main/demo_fundamental.py for how to do stuff.

**Comment by Parskatt** [comment]
I have now also updated the readme, https://github.com/Parskatt/DKM#readme :)

**Comment by zzxq2310** [comment]
> I have now also updated the readme, https://github.com/Parskatt/DKM#readme :)

Got it. Thank you very much!
