### ISSUE TITLE
About the pretrained model

### ISSUE THREAD

**Issue by CARRLIANSS** [Parskatt/DKM#34]
Hi Johan, I really appreciate your great work. Is it possible to provide the pretrained model here? Thank you very much!

**Comment by Parskatt** [comment]
It's loaded automatically when you call dkmv3_outdoor

**Comment by Parskatt** [comment]
https://github.com/Parskatt/storage/releases/tag/dkmv3

Heres the link

**Comment by CARRLIANSS** [comment]
Thank you very much! Good answer!
