### ISSUE TITLE
When using multi-GPU training, there is additional memory occupancy on GPU 0

### ISSUE THREAD

**Issue by qkqhd222** [Parskatt/DKM#38]
Thanks for releasing such a great package.
When I import dkm at my custom script, just importing makes additional memory occupancy on gpu 0.

![image](https://github.com/Parskatt/DKM/assets/4018231/14700a44-6757-4554-8305-a2315378de20)

Moving the following line to tensor_to_pil() seems to fix this.

imagenet_mean = torch.tensor([0.485, 0.456, 0.406]).to(device)
imagenet_std = torch.tensor([0.229, 0.224, 0.225]).to(device)

(https://github.com/Parskatt/DKM/blob/main/dkm/utils/utils.py#L294)

Could you check?

**Comment by Parskatt** [comment]
Hi, thanks for noticing! Could you submit a pull request with it fixed?
