### ISSUE TITLE
Pretrained weights licensing

### ISSUE THREAD

**Issue by stepankonev** [Parskatt/DKM#42]
Dear @Parskatt, dear authors, thank you for this repo! Great work!
Could you please clarify on the license of the provided DKMv3 model's weights for indoor and outdoor? Were they trained on datasets that imply open license?
Thank you in advance!

**Comment by Parskatt** [comment]
Indoor = scannet, scannet has non-commercial license I can not speak for whether this implies that the weights are non commercial. There is to my knowledge no legal predjudice.

Outdoor = megadepth, megadepth is MIT licensed, weights trained here are MIT

**Comment by stepankonev** [comment]
Thank you very much for your help! Good luck with further improvements:)
