### ISSUE TITLE
scannet test code

### ISSUE THREAD

**Issue by jdk9405** [Parskatt/DKM#54]
Hi,

Thank you for sharing your work. It's been helpful for my research.
However, I'm quite new to the dense matching method and have some simple questions regarding the scannet data test code.

I noticed that the error computing process is iterated five times. Is it a normal metric in other dense matching tasks like loftr or PDC-Net+?
https://github.com/Parskatt/DKM/blob/main/dkm/benchmarks/scannet_benchmark.py#L98
```
for _ in range(5):
    shuffling = np.random.permutation(np.arange(len(kpts1)))
    ...
```

Additionally, I saw another line that adds errors after the loop. This might include the same error twice.
https://github.com/Parskatt/DKM/blob/main/dkm/benchmarks/scannet_benchmark.py#L120
```
for _ in range(5):
    ...  
    tot_e_t.append(e_t)
    tot_e_R.append(e_R)
    tot_e_pose.append(e_pose)
tot_e_t.append(e_t)
tot_e_R.append(e_R)
tot_e_pose.append(e_pose)
```

Thanks in advance.

**Comment by Parskatt** [comment]
Hi! The first thing is to reduce the variance, the second thing is a bug (although not a severe one), good find!

Could you submit a pr to just remove that unneeded line?
