### ISSUE TITLE
With Synthetic Dataset Training Codes

### ISSUE THREAD

**Issue by TWJianNuo** [Parskatt/DKM#7]
Hi! 

While trying to rerpduce the results using Mega + Synthetic Dataset using "train_mega_synthetic.py", I notice that in the training code, model is set to be DKM (version 1), in Line 31-33. Does this indicate the training scripts "train_mega_synthetic.py" is designed for DKM (v1). Or the scripts are suitable for both versions?

Thanks!

**Comment by Parskatt** [comment]
Hi again. I no longer recommend training with synthetic data. We mainly did this for comparison with PDCNet.
I will push an indoor version which is trained on megadepth + scannet, which we found to work the best.

**Comment by Parskatt** [comment]
Also, apologies for things not being consistent, the code is still in active development and the public version may change over time.

**Comment by Parskatt** [comment]
@TWJianNuo The training is now updated for DKMv2, including scannet training. For scannet you need to download the scannet dataset and indices (see https://github.com/zju3dv/LoFTR/blob/master/docs/TRAINING.md). Note that we only used every 10 frames, since the full scannet dataset is extremely large.

**Comment by Parskatt** [comment]
@TWJianNuo yes, the pre print contains our previous approach with synthetic data and is not up to date. We are continously improving the approach and will soon (in around a month) release an updated preprint. Im dorry if this complicates any reproducing from your part.

**Comment by TWJianNuo** [comment]
Not at all! I really appreciate your prompt reply and well-maintained codebase!

Thanks!
