### ISSUE TITLE
Match Score

### ISSUE THREAD

**Issue by atharvjairath** [Parskatt/DKM#8]
Hey! 
First of all great work, I was wondering if we can get a match score of 2 images from this model?

**Comment by Parskatt** [comment]
Hi!

Sure, you could for example take the average of the dense confidence. This gives you an estimate of how much the images overlap.

**Comment by atharvjairath** [comment]
```
flow, confidence = dkm_model.match(im1, im2)
print(confidence.mean())
```
you mean something like above? if not please feel free to suggest. Thanks :)

**Comment by atharvjairath** [comment]
@Parskatt 
Cool thank you, will explore further.
